# Generated by Django 4.0.6 on 2022-07-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='acccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('choose_center', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
