# Generated by Django 4.0.6 on 2022-07-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0006_sigin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='acccount',
            new_name='account',
        ),
    ]
