# Generated by Django 4.0.6 on 2022-07-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0007_rename_acccount_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_new_manu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product')),
                ('Tiffin_Name', models.CharField(max_length=100, null=True)),
                ('Tiffin_Price', models.IntegerField(null=True)),
                ('Offer_price', models.IntegerField(null=True)),
                ('Description', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
