# Generated by Django 4.0.6 on 2022-07-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0011_alter_account_id_alter_add_new_manu_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='edit_manu',
        ),
    ]
