# Generated by Django 4.0.6 on 2022-07-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0012_delete_edit_manu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_new_manu',
            name='image',
        ),
    ]
