# Generated by Django 4.0.6 on 2022-07-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0014_add_new_manu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_new_manu',
            name='image',
        ),
    ]
