# Generated by Django 4.0.6 on 2022-07-20 06:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0016_add_new_manu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DateField(default=datetime.datetime.today)),
                ('add_manu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.add_new_manu')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.sigin')),
            ],
        ),
    ]
