# Generated by Django 4.0.6 on 2022-07-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0020_add_new_manu_categery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_new_manu',
            old_name='categery',
            new_name='categery_id',
        ),
    ]
