# Generated by Django 4.0.6 on 2022-07-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0025_remove_add_new_manu_categery_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_new_manu',
            name='categery_id',
        ),
        migrations.AddField(
            model_name='add_new_manu',
            name='categery_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
