# Generated by Django 4.0.6 on 2022-07-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0027_alter_add_new_manu_categery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_manu',
            name='categery_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
