# Generated by Django 4.0.6 on 2022-07-25 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0029_alter_add_new_manu_categery_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.sigin')),
            ],
        ),
        migrations.CreateModel(
            name='OderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('orderlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.orderlist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.add_new_manu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.sigin')),
            ],
        ),
    ]
