# Generated by Django 4.0.6 on 2022-07-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0031_remove_oderitem_total_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_new_manu',
            name='categery_name',
        ),
        migrations.AddField(
            model_name='add_new_manu',
            name='category_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
