# Generated by Django 4.0.6 on 2022-07-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0034_alter_oderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.sigin'),
        ),
    ]
