# Generated by Django 4.0.6 on 2022-07-28 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiffinapp', '0036_alter_oderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
