# Generated by Django 4.0.6 on 2022-07-29 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0040_alter_add_new_manu_categery_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigin',
            name='choose_center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.center'),
        ),
    ]
