# Generated by Django 4.0.6 on 2022-08-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0045_alter_sigin_choose_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_new_manu',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
