# Generated by Django 4.0.6 on 2022-08-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0046_add_new_manu_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_new_manu',
            old_name='time',
            new_name='start_time',
        ),
    ]
