# Generated by Django 4.0.6 on 2022-08-16 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0048_add_new_manu_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_new_manu',
            name='choose_center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.center'),
        ),
    ]
