# Generated by Django 4.0.6 on 2022-08-18 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0050_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.account'),
        ),
    ]
