# Generated by Django 4.0.6 on 2022-08-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0051_rename_name_account_username_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='Name',
        ),
    ]
