# Generated by Django 4.0.6 on 2022-08-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0052_rename_username_account_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Name',
            new_name='username',
        ),
    ]
