# Generated by Django 4.0.6 on 2022-08-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0055_alter_add_new_manu_categery_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_new_manu',
            name='categery_name',
        ),
        migrations.RemoveField(
            model_name='add_new_manu',
            name='choose_center',
        ),
    ]
