# Generated by Django 4.0.6 on 2022-08-20 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0056_remove_add_new_manu_categery_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_new_manu',
            name='categery_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.category'),
        ),
        migrations.AddField(
            model_name='add_new_manu',
            name='choose_center',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.center'),
        ),
    ]
