# Generated by Django 4.0.6 on 2022-08-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0063_alter_account_choose_center'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('username',)},
        ),
        migrations.AlterModelOptions(
            name='center',
            options={'ordering': ('city',)},
        ),
        migrations.AlterField(
            model_name='account',
            name='choose_center',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choose_center', to='tiffinapp.center'),
        ),
    ]
