# Generated by Django 4.0.6 on 2022-08-23 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0071_remove_account_choose_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='choose_center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.center'),
            preserve_default=False,
        ),
    ]
