# Generated by Django 4.0.6 on 2022-08-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinapp', '0075_alter_account_choose_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='Date',
        ),
    ]
