# Generated by Django 4.0.6 on 2022-08-24 09:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiffinapp', '0076_rename_price_order_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderList',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='OderItem',
            new_name='CartItem',
        ),
    ]
