# Generated by Django 4.0.6 on 2022-08-24 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiffinapp', '0078_rename_orderlist_cartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='Cart',
            new_name='OrderList',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.AddField(
            model_name='oderitem',
            name='orderlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.orderlist'),
        ),
        migrations.AddField(
            model_name='oderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiffinapp.add_new_manu'),
        ),
        migrations.AddField(
            model_name='oderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
