# Generated by Django 4.0.6 on 2022-08-24 13:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiffinapp', '0080_delete_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderList',
            new_name='Order',
        ),
    ]
